[versions]
kotlin = "1.6.10"
kotlinx-serialization = "1.3.2"
kotlinx-coroutines = "1.6.0"
slf4j = "1.7.36"

# Used for example, not included in KDiscordIPC
log4j = "2.17.1"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Used for example, not included in KDiscordIPC
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
